name: CI/CD Pipeline - PetClinic
 
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]


env:
  JAVA_VERSION: '25'
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_PROJECT_KEY: ${{ vars.SONAR_PROJECT_KEY }}
  SONAR_ORGANIZATION: ${{ vars.SONAR_ORGANIZATION }}
  VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
  VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
  VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
  VAULT_JFROG_PATH: secrets/creds/jfrog
  JFROG_URL: ${{ secrets.JFROG_URL }}
  JFROG_REPO: 'devops-project'
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
  ECS_SERVICE: ${{ secrets.ECS_SERVICE }}
 
jobs:
 gitleaks:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
 
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}